{% set name = "mmh3" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hajimes/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 0b476dd6f83172cfb3bfec534e78011d9d86efe803182f1932b3566fb9128659

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - mmh3
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/hajimes/mmh3
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
  description: |
    mmh3 is a Python wrapper for MurmurHash (MurmurHash3), a set of fast 
    and robust non-cryptographic hash functions invented by Austin Appleby.
  dev_url: https://github.com/hajimes/mmh3
  doc_url: https://github.com/hajimes/mmh3/blob/master/README.md
extra:
  recipe-maintainers:
    - johnlees
