{% set name = "mmh3" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hajimes/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: c83aa26569eb83d230cf83f0a673d2f0cde713e02d5be5f6ae7c7a3be7059532

build:
  number: 0
  skip: True # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - mmh3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/hajimes/mmh3
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
  dev_url: https://github.com/hajimes/mmh3
  doc_url: https://github.com/hajimes/mmh3/blob/master/README.md
extra:
  recipe-maintainers:
    - johnlees
