travis:
  secure:
    BINSTAR_TOKEN: XEjeEaXugs1RnCW3dm6UbRDbM4bus8VO2yQXOjpohWuhdpB2Yg0tVs98iz/lt8qxdQbctaaliAkLdcIc05OyLJklchgALhmTKTKcio9d239oLt47ab0dr6V6ary1PjFMAelFViMAJVDz/eKnyi2yN7EPSxkMKtXeN/+jzmGhdxZDfC2E8nvHrbgD68nCWxRvzU1LhLAQP5/NvBHzUJiulCpZEgPfk5PWBaOGeQ6H8LJN67V9aIcW6hJRaynRHhExtckbKctvSAwjifk7+2n3tALu4RKV7Z21HrxRkwANgTjUo7Rg5plPU5CTL/5yB68rGtCSfExNTvVB9P7m3mf5l0b+tJTedNFrci8mb856axlTdlRDXP1y6Obqt4weR91ImlkWZbAmW/8+f1EbFhBnD/sUNzk28G/UVNX/+TriYNr5hkgFtXanMHqL/4aOuoz949PUWOoliSsdlHM7F33H4dSMASrzQhZUR057o/gMkmnlvHmvuys1OG3/ulOIAClZud0bc0Hazmk3CXNEixLLj9etnkczZiJ80ZcWprZ2CqQf9IWJ6ev88JYiKpK/Ruu+8x6hWTh//wFjiLYxXgWT0jhkabP/rLQ0FPshROHBGILGX7Ow5+SJeUGpqRQDaK9/O46w+pz3yuyw3rDimQxbPGiIi0CG85l5gKhcVAycEgw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
